name: cifar100_imb001
print_freq: 40
workers: 4
log_dir: 'logs'
model_dir: 'ckps'


# dataset & model setting
dataset: 'cifar100'
data_path: './data/cifar100'
num_classes: 100
imb_factor: 0.01
backbone: 'resnet32_fe'
feat_size: 64
resume: ''
head_class_idx:
  - 0
  - 36
med_class_idx:
  - 36
  - 71
tail_class_idx:
  - 71
  - 100


# distributed training
deterministic: True
distributed: False
gpu: null
world_size: -1
rank: -1
dist_url: 'tcp://224.66.41.62:23456'
dist_backend: 'nccl'
multiprocessing_distributed: False


# Train
mode: 'stage1'
lr: 0.2
batch_size: 128
weight_decay: 2e-4
num_epochs: 200
momentum: 0.9
cos: False
mixup: False
alpha: 1.0
start_aug: 10
end_aug: 3
fit_thresh: 0.8
bank_size: 128
